### ISSUE TITLE
zsh-autosuggestions (in antigen?) breaks some keybindings

### ISSUE THREAD

**Issue by legovini** [tarruda/zsh-autosuggestions#29]
I'm trying to use zsh-autosuggestions with antigen, apparently it works, but it breaks some keybindings:

1. The Home and End key do nothing, but ^A and ^E still work to move the cursor to the beginning and end of line;
2. ^C has to be pressed two times to kill the line (^U still works, but I find ^C more convenient);
3. The right arrow does not accept the autosuggestion, but here I'm not sure if it is supposed to do so.

It does not matter if I add "antigen use oh-my-zsh" in my zshrc, I still get these problems. No errors are printed.

If you need me to perform any test just let me know.
Thanks!

**Comment by faceleg** [comment]
Fixed now?

**Comment by k4nar** [comment]
The completion is still broken. For example git commands are not completed, only files are.

**Comment by jhass** [comment]
Happens for me too, Home and End are not working. German keyboard and Terminology as terminal emulator.

**Comment by ronjouch** [comment]
I am also affected by @legovini's sub-issue 1:

* With zsh-autosuggestions installed, the `Home` and `End` keys fail to move the cursor to the beginning and end of the line...
* ... but `^A` and `^E` still work...
* .... and deinstalling zsh-autosuggestions restore working `Home` and `End`.

I run gnome-terminal-3.16, zsh-5.0.8, oh-my-zsh, and load zsh-autosuggestions with:

```bash
source $HOME/.zsh-autosuggestions/autosuggestions.zsh
unset COMPLETION_WAITING_DOTS # https://github.com/tarruda/zsh-autosuggestions#known-issues
AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=3'
zle-line-init() {
  zle autosuggest-start
}
zle -N zle-line-init
```

Any idea?

**Comment by ronjouch** [comment]
@legovini as I use oh-my-zsh, this is not an antigen issue. Can you update the issue title?

**Comment by ronjouch** [comment]
Workaround if you use tmux \o/ ! In your `~/.tmux.conf` ,

```
# move to next/prev word with Ctrl, http://stackoverflow.com/questions/9444900/settings-to-move-to-end-of-line-using-tmux
bind -n C-left send-keys M-b
bind -n C-right send-keys M-f
```

**Comment by ericfreese** [comment]
I don't think this is still an issue w/ v0.1.x.
